# Generated by Django 2.0 on 2019-08-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_reder_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='reder_num',
            new_name='readed_num',
        ),
    ]
